config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}

  root 'welcome#index'

  resources :users, only: [:index, :show] # do

  get '/titles', to: "items#titles"
  post '/titles', to: "items#get_titles"

  get "/items/new_wanted", to: "items#new_wanted"
  get "/items/from_title", to: "items#from_title"

  resources :items do
    collection { post :search, to: 'items#search' }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable
         # , :confirmable
         # , :omniauthable

  has_one :library
  has_one :wanted_list
  before_create :prepare_user
  geocoded_by :location
  after_validation :geocode

  def prepare_user
    self.library = Library.create
    self.wanted_list = WantedList.create
  end

  def add_to_library(item)
    self.library.add(item)
  end

  def add_to_wanted_list(item)
    self.wanted_list.add(item)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # def us_states
  #   [
  #     ['Alabama', 'AL'],
  #     ['Alaska', 'AK'],
  #     ['Arizona', 'AZ'],
  #     ['Arkansas', 'AR'],
  #     ['California', 'CA'],
  #     ['Colorado', 'CO'],
  #     ['Connecticut', 'CT'],
  #     ['Delaware', 'DE'],
  #     ['District of Columbia', 'DC'],
  #     ['Florida', 'FL'],
  #     ['Georgia', 'GA'],
  #     ['Hawaii', 'HI'],
  #     ['Idaho', 'ID'],
  #     ['Illinois', 'IL'],
  #     ['Indiana', 'IN'],
  #     ['Iowa', 'IA'],
  #     ['Kansas', 'KS'],
  #     ['Kentucky', 'KY'],
  #     ['Louisiana', 'LA'],
  #     ['Maine', 'ME'],
  #     ['Maryland', 'MD'],
  #     ['Massachusetts', 'MA'],
  #     ['Michigan', 'MI'],
  #     ['Minnesota', 'MN'],
  #     ['Mississippi', 'MS'],
  #     ['Missouri', 'MO'],
  #     ['Montana', 'MT'],
  #     ['Nebraska', 'NE'],
  #     ['Nevada', 'NV'],
  #     ['New Hampshire', 'NH'],
  #     ['New Jersey', 'NJ'],
  #     ['New Mexico', 'NM'],
  #     ['New York', 'NY'],
  #     ['North Carolina', 'NC'],
  #     ['North Dakota', 'ND'],
  #     ['Ohio', 'OH'],
  #     ['Oklahoma', 'OK'],
  #     ['Oregon', 'OR'],
  #     ['Pennsylvania', 'PA'],
  #     ['Puerto Rico', 'PR'],
  #     ['Rhode Island', 'RI'],
  #     ['South Carolina', 'SC'],
  #     ['South Dakota', 'SD'],
  #     ['Tennessee', 'TN'],
  #     ['Texas', 'TX'],
  #     ['Utah', 'UT'],
  #     ['Vermont', 'VT'],
  #     ['Virginia', 'VA'],
  #     ['Washington', 'WA'],
  #     ['West Virginia', 'WV'],
  #     ['Wisconsin', 'WI'],
  #     ['Wyoming', 'WY']
  #   ]
  # end
end

app/views/users/show.html.haml
#profile
  #user-info
    %h3= @user.username
    %p
      Location: 
      = @user.location
    - if @user == current_user
      =link_to "Edit Profile", edit_user_registration_path
    - elsif current_user
      = number_with_precision(@user.distance_from(current_user), precision: 2)
      miles away

  #map
    %input#user_location{type: 'hidden', value: @user.location}
    #map-canvas{style: "width: 800px; height: 400px;"}

  #library
    %h3 For Rent
    - if @user == current_user
      =link_to "Add New Item +", new_item_path, id: "new_library_item", class: "new-item-link"
    - @user.library.items.each do |i|
      = render partial: "items/item", locals: {item: i}

  #wanted-list
    %h3 Wanted
    - if @user == current_user
      =link_to "Add New Item +", items_new_wanted_path, id: "new_wanted_list_item", class: "new-item-link"
    - @user.wanted_list.items.each do |i|
      = render partial: "items/item", locals: {item: i}