config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}

  root 'welcome#index'

  resources :users, only: [:index, :show] # do

  get '/titles', to: "items#titles"
  post '/titles', to: "items#get_titles"

  get "/items/new_wanted", to: "items#new_wanted"
  get "/items/from_title", to: "items#from_title"

  resources :items do
    collection { post :search, to: 'items#search' }
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_list
  has_one :user, through: :item_list
  mount_uploader :images, ItemImageUploader

  def proper_class_name
    self.class.proper_class_name
  end

  def self.type_names
    self.descendants.map{|d| d.proper_class_name}
  end

  def self.type_symbols
    self.descendants.map{|d| d.class_symbol}
  end

  def self.type_symbols_plural
    self.descendants.map{|d| d.class_symbol.to_s.pluralize.to_sym}
  end

  def self.proper_class_name
    self.name.gsub(/(?=[A-Z])/, ' ').strip!
  end

  def self.class_symbol
    self.name.gsub(/(?=[A-Z])/, ' ').strip!.gsub(/\s/, '_').downcase.to_sym
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @search = Item.search(params[:q])
    # @items = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

  def search
    @search = Item.search(params[:q])
    @items = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
    render partial: "listings", layout: false
  end

  def for_rent
    @items = items_of_list_type(:Library)
  end

  def wanted
    @items = items_of_list_type(:WantedList)
  end

  def titles
    @input = params["titles"] || {}
  end

  def get_titles
    @results = {}
    @input = params["titles"] || {}
    if !@input.empty?
      keywords = @input[:keywords].gsub(/[^a-zA-Z0-9\s]/, '')
      if keywords.length > 0
        Item.type_symbols_plural.each do |s|
          @results[s] = send("#{s.to_s}_api", keywords) if @input[s] == "1"
        end
      end
    end
    render partial: "/items/title_results/index", layout: false
  end

  def from_title
    if params[:library]
      redirect_to new_item_path(params)
    elsif params[:wanted_list]
      redirect_to items_new_wanted_path(params)
    else 
      redirect_to titles_path
    end
  end

  def new
  end

  def new_wanted
  end

  def create
    if current_user
      item_params = params["item"].except("type", "wanted").to_h
      model = params["item"]["type"].gsub(' ', '').constantize
      is_wanted = params["item"]["wanted"] == "true"

      item = model.create(item_params)
      # params["item"]["images"].each do |i|
      #   item.images = i
      # end

      method_name = "add_to_#{is_wanted ? 'wanted_list' : 'library'}"
      if current_user.send(method_name, item)
        flash.notice = "#{item.name} (#{item.proper_class_name}) has successfully been added to your #{is_wanted ? 'list of wanted items' : 'library'}."
        # redirect_to is_wanted ? user_wanted_lists_path(current_user) : user_libraries_path(current_user)
        redirect_to user_path(current_user)
      else
        flash.alert = "Item could not be created"
        redirect_to new_item_path
      end
    else
      flash.alert = "You must be signed in to do that"
      redirect_to new_user_session_path 
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    attributes = params[:item].select{ |key, p| !p.blank? }.permit(:name)

    Item.update(params[:id], attributes)

    redirect_to user_path(current_user)
  end

  def destroy
    Item.destroy(params[:id])
    redirect_to user_path(current_user)
  end

  private

  def items_of_list_type(type)
    ItemList.where("type = ?", type).reduce([]){ |items, current_library| items.concat(current_library.items) }
  end

  def books_api(keywords)
    Unirest.get("https://www.googleapis.com/books/v1/volumes?key=#{ENV["books_key"]}&q=#{keywords}",).body["items"]
  end

  def movies_api(keywords)
    Unirest.get("http://api.rottentomatoes.com/api/public/v1.0/movies.json?apikey=#{ENV["movies_key"]}&q=#{keywords}",).body["movies"]
  end

  def video_games_api(keywords)
    Unirest.get("http://www.giantbomb.com/api/search/?api_key=#{ENV["video_games_key"]}&format=json&query=#{keywords}&resources=game").body["results"]
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_condition_fields.html.haml
.field.condition
  = f.attribute_fields do |a|
    = a.attribute_select associations: [:category]
  = f.predicate_select
  = f.value_fields do |v|
    = v.text_field :value
  = link_to "remove", '#', class: "remove_fields"

app/views/items/_item.html.haml
%a{href: item_path(item) }
  .item-display{class: "#{item.type.downcase}"}
    - src = !item.images.blank? ? item.images : "no_image.png"
    .img-wrap= image_tag src
    .info
      .name= item.name
      .desc= item.description
      / .icon= image_tag "icons/#{item.type.downcase}.png"
    / - if item.user
    /   %li
    /     Owned by
    /     = link_to item.user.username, user_path(item.user)}

app/views/items/_listings.html.haml
- if @items
  - @items.each do | item |
    = render partial: "item", locals: {item: item}

app/views/items/_new_item_form.html.haml
- wanted = false if !wanted
- autofill_params = params[:item] || {}
= simple_form_for :item, url: items_path do |f|
  = f.input :name, label: "Item name", input_html: { value: autofill_params[:name] } #, readonly: !autofill_params.empty? }
  - item_type_names = Item.type_names
  / - [false, true].each do |is_hidden|
  /   = f.input :type, label: !is_hidden ? "Item type" : false, collection: item_type_names, :selected => autofill_params[:type] || item_type_names[0], input_html: { disabled: (is_hidden && autofill_params.empty?) || !(is_hidden || autofill_params.empty?), hidden: is_hidden }
  = f.input :type, label: "Item type", collection: item_type_names, :selected => autofill_params[:type] || item_type_names[0]
  = f.file_field :images, required: false #, multiple: true
  / = f.input :image_url, required: false
  / = f.label "Rent terms"
  / = f.input :min_duration, input_html: { value: number_with_precision(1, precision: 0) }
  / = f.input :max_duration, input_html: { value: number_with_precision(7, precision: 0) }
  / = f.input :rate, input_html: { value: number_with_precision(1, precision: 2) }
  = f.input :description, as: :text, required: false
  = f.hidden_field :wanted, :value => wanted
  = f.submit "Add New Item"

app/views/items/edit.html.haml
= simple_form_for @item, as: :item, url: item_path do |f|
  = f.input :name, label: "Item name"
  - item_type_names = Item.type_names
  = f.input :type, label: "Item type", collection: item_type_names
  = f.label "Rent terms"
  / = f.input :min_duration
  / = f.input :max_duration
  / = f.input :rate
  = f.submit "Save Changes"

app/views/items/index.html.haml
%h3 All Items

- content_for(:side) do
  = search_form_for @search, url: search_items_path, method: :post, remote: true do |f|
    = f.condition_fields do |c|
      = render "condition_fields", f: c
    %p= link_to_add_fields "Add Conditions", f, :condition
    .field
      Sort:
      = f.sort_fields do |s|
        = s.sort_select
    .actions= f.submit "Search"

- content_for(:body) do
  #listings

app/views/items/new.html.haml
= render :partial => "new_item_form"

app/views/items/new_wanted.html.haml
= render :partial => "new_item_form", :locals => { wanted: true }

app/views/items/show.html.haml
%ul
  %li= @item.name
  - if !@item.images.blank?
    %li= image_tag @item.images
  %li
    Owned by
    = link_to @item.user.username, user_path(@item.user)

- if @item.user == current_user
  = simple_form_for @item, url: item_path(@item), method: "DELETE" do |f|
    = f.submit "Delete"
  = simple_form_for @item, url: edit_item_path(@item), method: "GET" do |f|
    = f.submit "Edit"

app/views/items/titles.html.haml
- @input = {} if @input.nil?
- @results = {} if @results.nil?
- content_for(:nav) do
  - type_symbols = Item.type_symbols_plural
  = simple_form_for :titles, remote: true, html: { class: "titles columns-#{type_symbols.length}" } do |f|
    = f.input :keywords, label: false, input_html: { value: @input[:keywords] }
    = f.submit "Search"
    - type_symbols.each do |s|
      = f.input s, as: :boolean, input_html: { checked: @input[s] != "0" }
.header
  %h3 Titles
  %p - Search for titles that you want to post in your listings
= render partial: "/items/title_results/index", layout: false