config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'registrations'}

  root 'welcome#index'

  resources :users, only: [:index, :show] # do

  get '/titles', to: "items#titles"
  post '/titles', to: "items#get_titles"

  get "/items/new_wanted", to: "items#new_wanted"
  get "/items/from_title", to: "items#from_title"

  resources :items do
    collection { post :search, to: 'items#search' }
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :item_list
  has_one :user, through: :item_list
  mount_uploader :images, ItemImageUploader

  def proper_class_name
    self.class.proper_class_name
  end

  def self.type_names
    self.descendants.map{|d| d.proper_class_name}
  end

  def self.type_symbols
    self.descendants.map{|d| d.class_symbol}
  end

  def self.type_symbols_plural
    self.descendants.map{|d| d.class_symbol.to_s.pluralize.to_sym}
  end

  def self.proper_class_name
    self.name.gsub(/(?=[A-Z])/, ' ').strip!
  end

  def self.class_symbol
    self.name.gsub(/(?=[A-Z])/, ' ').strip!.gsub(/\s/, '_').downcase.to_sym
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @search = Item.search(params[:q])
    # @items = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

  def search
    @search = Item.search(params[:q])
    @items = @search.result
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
    render partial: "listings", layout: false
  end

  def for_rent
    @items = items_of_list_type(:Library)
  end

  def wanted
    @items = items_of_list_type(:WantedList)
  end

  def titles
    @input = params["titles"] || {}
  end

  def get_titles
    @results = {}
    @input = params["titles"] || {}
    if !@input.empty?
      keywords = @input[:keywords].gsub(/[^a-zA-Z0-9\s]/, '')
      if keywords.length > 0
        Item.type_symbols_plural.each do |s|
          @results[s] = send("#{s.to_s}_api", keywords) if @input[s] == "1"
        end
      end
    end
    render partial: "/items/title_results/index", layout: false
  end

  def from_title
    if params[:library]
      redirect_to new_item_path(params)
    elsif params[:wanted_list]
      redirect_to items_new_wanted_path(params)
    else 
      redirect_to titles_path
    end
  end

  def new
  end

  def new_wanted
  end

  def create
    if current_user
      item_params = params["item"].except("type", "wanted").to_h
      model = params["item"]["type"].gsub(' ', '').constantize
      is_wanted = params["item"]["wanted"] == "true"

      item = model.create(item_params)
      # params["item"]["images"].each do |i|
      #   item.images = i
      # end

      method_name = "add_to_#{is_wanted ? 'wanted_list' : 'library'}"
      if current_user.send(method_name, item)
        flash.notice = "#{item.name} (#{item.proper_class_name}) has successfully been added to your #{is_wanted ? 'list of wanted items' : 'library'}."
        # redirect_to is_wanted ? user_wanted_lists_path(current_user) : user_libraries_path(current_user)
        redirect_to user_path(current_user)
      else
        flash.alert = "Item could not be created"
        redirect_to new_item_path
      end
    else
      flash.alert = "You must be signed in to do that"
      redirect_to new_user_session_path 
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    attributes = params[:item].select{ |key, p| !p.blank? }.permit(:name)

    Item.update(params[:id], attributes)

    redirect_to user_path(current_user)
  end

  def destroy
    Item.destroy(params[:id])
    redirect_to user_path(current_user)
  end

  private

  def items_of_list_type(type)
    ItemList.where("type = ?", type).reduce([]){ |items, current_library| items.concat(current_library.items) }
  end

  def books_api(keywords)
    Unirest.get("https://www.googleapis.com/books/v1/volumes?key=#{ENV["books_key"]}&q=#{keywords}",).body["items"]
  end

  def movies_api(keywords)
    Unirest.get("http://api.rottentomatoes.com/api/public/v1.0/movies.json?apikey=#{ENV["movies_key"]}&q=#{keywords}",).body["movies"]
  end

  def video_games_api(keywords)
    Unirest.get("http://www.giantbomb.com/api/search/?api_key=#{ENV["video_games_key"]}&format=json&query=#{keywords}&resources=game").body["results"]
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/title_results/_books.html.haml
- volume_info = result["volumeInfo"]
- if volume_info
  - @item_data[:name] = volume_info["title"]
  - x = volume_info["imageLinks"]
  - @item_data[:image] = x["thumbnail"] if !x.nil?

app/views/items/title_results/_index.html.haml
- dirname = "items/title_results"
- @results.select!{ |key, r| !r.empty? }
#titles{ class: "columns-#{@results.length}" }
  - Item.type_symbols_plural.each do |s|
    - if @results[s]
      %div{ id: s }
        %ul
          - Kaminari.paginate_array(@results[s]).page(1).per(3).each do | result |
            - @item_data = {}
            = render partial: "#{dirname}/#{s.to_s}", locals: { result: result }
            - @item_data[:type] = s.to_s.classify.constantize.proper_class_name
            %li= @item_data[:name]
            - src = !@item_data[:image].blank? ? @item_data[:image] : 'no_image.png'
            %li= image_tag src
            = simple_form_for :item, url: items_from_title_path, method: :get, defaults: { as: :hidden } do |f|
              = f.input :name, input_html: { value: @item_data[:name] }
              = f.input :type, input_html: { value: @item_data[:type] }
              = f.submit "I Have This", name: :library
              = f.submit "I Want This", name: :wanted_list

app/views/items/title_results/_movies.html.haml
- @item_data[:name] = result["title"]
- images = result["posters"]
- @item_data[:image] = images["detailed"].gsub('_tmb', '_det') if images

app/views/items/title_results/_video_games.html.haml
- @item_data[:name] = result["name"]
- images = result["image"]
- @item_data[:image] = images["thumb_url"] if images